id: I0237775E
legacy_id: P009295
ocr_import_info:
  bdrc_scan_id: W30184
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T08:31:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:24:24.815502+00:00'
last_modified: 2022-09-03 19:25:07.669610
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30184
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30184
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་བསྟན་དར།
  author: ཨ་ལག་ཤ་བསྟན་དར།
statistics:
  ocr_word_mean_confidence_index: 0.8321610622234438
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I1KG10529:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10529
      total_pages: 766
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10529.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.8511228560753793
    legacy_id: v001
  I1KG10530:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10530
      total_pages: 784
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG10530.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8180106010965096
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
