id: I0237775E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T08:32:53+00:00'
last_modified: '2022-06-08T10:00:14.143519+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30184
  title: གསུང་འབུམ། ངག་དབང་བསྟན་དར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1CFE:
      image_group_id: I1KG10529
      title: ''
      total_pages: 766
      order: 1
      base_file: 1CFE.txt
    59D3:
      image_group_id: I1KG10530
      title: ''
      total_pages: 784
      order: 2
      base_file: 59D3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
